--- 
author: "Grigor Malo"
description: "Technology, creative coding, politics, philosophy, blogging, all sort of keywords to trick f***ing Google.\"\n"
email: grigormalo@gmail.com
markdown: kramdown
permalink: pretty
categories: experiments, dataviz, politics, philosophy, creative coding
social: 
  - 
    icon: twitter
    title: twitter
    url: "https://twitter.com/grigormalo"
  - 
    icon: github
    title: github
    url: "https://github.com/GrigorM"
  - 
    icon: envelope
    title: mail
    url: "mailto:grigormalo@gmail.com"
title: Disinnovate
url: grigorm.github.io/reclaim/
