# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: grigorm.github.io/reclaim/
title: Disinnovate
email: grigormalo@gmail.com
author: Grigor Malo
description: > # "Write an awesome description for your new site here. 
  Technology, creative coding, politics, philosophy, blogging, all sort of keywords to trick f***ing Google."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: twitter
  title: twitter
    url: https://twitter.com/grigormalo

  - title: github
    url: https://github.com/GrigorM
icon: github
  - title: mail
    url: mailto:grigormalo@gmail.com
icon: envelope
	