	
# ----------------------- #
#      Main Configs       #
# ----------------------- #	
--- 
author: "Grigor Malo"
description: "Technology, creative coding, politics, philosophy, blogging, all sort of keywords to trick f***ing Google.\"\n"
email: grigormalo@gmail.com
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
social: 
  - 
    icon: twitter
    title: twitter
    url: "https://twitter.com/grigormalo"
  - 
    icon: github
    title: github
    url: "https://github.com/GrigorM"
  - 
    icon: envelope
    title: mail
    url: "mailto:grigormalo@gmail.com"
title: Disinnovate
url: grigorm.github.io/reclaim/
	
	